[package]
name = "fe_bucket"
version = "0.1.0"
authors = ["Matt Pindell <pindell.m@gmail.com>", "Regis Boudinot <boudinot.regis@yahoo.com>"]

[dependencies]
rustc-serialize = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
time = "*"
